train: /home/kjonghun0828/firewatcher_ai_learning/sample_data/images/train # train 데이터 경로
val: /home/kjonghun0828/firewatcher_ai_learning/sample_data/images/val     # validation 데이터 경로
test: /home/kjonghun0828/firewatcher_ai_learning/sample_data/images/test   # test 데이터 경로

nc: 6
names: ['흑색연기','백색/회색연기','화염','구름','안개/연무',굴뚝연기]